### ISSUE TITLE
Object with multiple arrays

### ISSUE THREAD

**Issue by kdauzickas** [bobthecow/genghis#20] opened 2012-07-07 00:22 UTC
Seems genghis cannot correctly save or display objects that have multiple arrays in them.
[![Error](http://desmond.imageshack.us/Himg545/scaled.php?server=545&filename=screenshotfrom201207070.png&res=crop)](http://imageshack.us/f/545/screenshotfrom201207070.png/)

**Comment by bobthecow** [comment] 2012-07-07 00:34
Can you give me a sample document?

**Comment by kdauzickas** [comment] 2012-07-07 00:37
{"attributes" : [ "der", "dsa" ], "title" : "product one", "description" : "first test product", "created" : "2012-01-01", "active" : "yes", "deleted" : "no", "tags" : [ "tag1", "tag2", "tag3" ], "urlTitle" : "test-product-one" }

**Comment by patrickgalbraith** [comment] 2012-08-24 09:24
This happened to me too however the issue doesn't have anything to do with arrays.

It is caused by using a key called `attributes`.

This works:

```
{
    "attributes2": [1, 2]
}
```

This doesn't work:

```
{
    "attributes": [1, 2]
}
```

**Comment by bobthecow** [comment] 2012-08-25 01:32
In Backbone.js Model classes, `attributes` is a magic property — that's where all the actual model values are stored. This probably had something to do with this.

I've updated to the latest version of Backbone in the `develop` branch. I can't reproduce this bug there, so I think it's probably fixed. Do me a favor and check out the latest version and let me know if it isn't fixed?

https://github.com/bobthecow/genghis/tree/develop

**Comment by patrickgalbraith** [comment] 2012-08-25 10:35
@bobthecow thanks I can confirm that the latest from the develop branch works well.

**Comment by bobthecow** [comment] 2012-09-05 19:06
Great, thank you.

Resolving this issue, it'll be released in the upcoming v2.0 release.

**Closed as completed by bobthecow** 2012-09-05 19:06 UTC
Labels: bug
