### ISSUE TITLE
error "DateTime is not currently supported" when saving edited document

### ISSUE THREAD

**Issue by jan-harmsen** [bobthecow/genghis#48] opened 2012-10-24 20:57 UTC
steps to reproduce (genghis version 2.1.2 with MongoDB v2.2.1-rc0):
1. display a document containing at least one DateTime 
2. start editing document (not modifying any DateTime)
3. save document (triggering PUT)

document does not get saved, Firebug shows error with status code 500:

``` json
{
"error":"DateTime is not currently supported; use a UTC Time instance instead.",
"status":500
}
```

and rails console reports:

BSON::InvalidDocument - DateTime is not currently supported; use a UTC Time instance instead.: .../gems/bson-1.7.0/lib/bson/bson_c.rb:24:in `serialize'
.....
/gems/genghisapp-2.1.2/genghis.rb:245:in`update'

**Comment by bobthecow** [comment] 2012-10-24 21:05
I'll look into this later this afternoon. In the meantime, what versions of the following are you using:
- genghisapp gem
- bson_ext gem
- mongo gem
- ruby

Thanks!

**Comment by jan-harmsen** [comment] 2012-10-24 21:09
- genghisapp (2.1.2)
- bson_ext (1.7.0)
- mongo (1.7.0)
- ruby 1.9.3-p286

No hurry, take your time, you've created a really nice utility app!

**Comment by bobthecow** [comment] 2012-10-27 16:37
I'm unable to reproduce this with MongoDB v2.2.0 (and all the other versions you list). I'll try to get v2.2.1-rc0 running and see if I can reproduce it there.

Curious: does it happen when you run Genghis as a standalone app, or only when mounted under Rails? Try running `genghisapp` and see whether that has the same problem.

**Comment by jan-harmsen** [comment] 2012-10-29 17:23
Hi, I am able to reproduce it, behaviour is as follows:
- editing works all the time with genghisapp
- editing a document containing a DateTime via genghis mounted in Rails works only the first time but not the second (third etc.) time:
  When editing and saving the document the first time, the formatting changes from

``` javascript
doc_updated_at: ISODate("2012-10-29T17:07:37+00:00")
```

to

``` javascript
doc_updated_at: ISODate("Mon Oct 29 2012 18:07:38 GMT+0100 (CET)")
```

and after that it's no longer possible to save an edited document since an error is thrown (see my first posting).

Hope that helps...

**Comment by bobthecow** [comment] 2012-10-29 17:31
Grr. Rails must be fiddling with something. I'll try to track it down.

**Comment by jan-harmsen** [comment] 2012-10-29 17:33
Grrrreat, THANKS :-)

**Comment by bobthecow** [comment] 2012-10-29 19:04
Got it. Something railsy is 'fixing' DateTime#to_time to return a DateTime instance instead of a Time instance. I've got a workaround, but I'm looking for a better way :-/

**Comment by jan-harmsen** [comment] 2012-10-29 19:54
that's good news, thank you very much for looking into this!

**Comment by bobthecow** [comment] 2012-10-29 20:17
Okay. This should do it.

Do you mind checking against the develop branch and making sure it fixes things for you?

**Comment by jan-harmsen** [comment] 2012-10-29 20:35
OK, i will check tomorrow!

**Comment by jan-harmsen** [comment] 2012-10-30 13:36
OK, just tested your fix from branch 'develop': works like a charm, thanks a lot!

**Comment by bobthecow** [comment] 2012-10-30 15:57
Great. Thank you for your help. This will be in the next release (coming shortly).

**Comment by bobthecow** [comment] 2012-11-01 05:43
Annnd released.

**Closed as completed by bobthecow** 2012-11-01 05:43 UTC
Labels: bug
