### ISSUE TITLE
Connection to nodjitsu's MongoHQ hosted database's seems to never authenticate.

### ISSUE THREAD

**Issue by bambeano** [bobthecow/genghis#53] opened 2012-11-02 21:46 UTC
mongodb://nodejitsu:mypassword@alex.mongohq.com:10066/nodejitsudbsudoname

**Comment by bobthecow** [comment] 2012-11-02 21:58
This is true. It'll be fixed in the next release.

Closing as a dupe of #16

**Closed as completed by bobthecow** 2012-11-02 21:58 UTC
