### ISSUE TITLE
404s and empty pages on single-document views (when ids are not Mongo-generated?)

### ISSUE THREAD

**Issue by julien-c** [bobthecow/genghis#19] opened 2012-07-06 17:11 UTC
I get 404s and empty pages when going into the "detailed" single-document view (e.g. `http://localhost/genghis/servers/localhost/databases/amazon_product/collections/similarities/documents/0060517123`) though I know these documents exist (they're listed in the "list" view, for one).

Not sure why, but this seems to only happen on collections where ids were not autogenerated by MongoDB (those are barcode-like natural ids).

**Comment by bobthecow** [comment] 2012-07-06 17:26
The issue is (probably) that Genghis implicitly wraps IDs in an ObjectId when requesting the object directly (GET, POST, DELETE):

https://github.com/bobthecow/genghis/blob/master/src/php/Genghis/Api.php#L389-432

This could probably be fixed by only wrapping it if the ID string is a 24 character hex string. Do me a favor and test this version, let me know if it works?

https://dl.dropbox.com/u/439174/genghis.php.tgz

**Comment by julien-c** [comment] 2012-07-06 17:32
It does!

(wow, impressive speed :)

**Comment by bobthecow** [comment] 2012-07-06 17:46
Cool. Feel free to keep using that version, and I'll get the fix into the next release.

**Closed as completed** 2012-07-06 18:04 UTC
