### ISSUE TITLE
No ajax response recieved for large collection from remote servers

### ISSUE THREAD

**Issue by aboosoyeed** [bobthecow/genghis#63] opened 2012-11-26 22:52 UTC
A consistent error that I have observed is that no response is recieved for large collections when sought from remote mongo server
http://screencloud.net/v/hiI7

I am not sure if the issue is with genghis or the php driver coz i have observed the issue on other UI clients like rockmongo

**Comment by bobthecow** [comment] 2012-11-26 23:21
It looks like a cursor timeout to me, but I've never experienced that. The collection size itself shouldn't matter as we're only fetching a page worth of documents at a time.

How big are the documents you're fetching? Does this happen with other collections or on other servers? Any chance you could drop a test script on the same box where your genghis.php is hosted and try to connect manually and fetch 25 documents?

**Comment by bobthecow** [comment] 2012-11-26 23:21
Even if it is a driver issue, there's a chance we can work around it. I've been able to work around almost every driver issue so far :)

**Comment by aboosoyeed** [comment] 2012-11-26 23:39
// the actual values have been replaced by [ ]
$m = new Mongo("mongodb://[server]");
$db = $m->[db];
$c="[collection]";
$collection = $db->{$c};
// find everything in the collection
$cursor = $collection->find()->limit(25);

// iterate through the results
foreach ($cursor as $obj) {
    print_r($obj);
}

// this threw "Unable to load the webpage because the server sent no data." So its a php driver issue it seems

**Comment by aboosoyeed** [comment] 2012-11-26 23:50
Interestingly when i ran this script using curl instead of the browser it did show a few values and repeatedly stops at 
 [_id] => MongoId Object
        (
       curl: (18) transfer closed with outstanding read data remaining
after showing a few documents

**Comment by bobthecow** [comment] 2012-11-27 01:09
Stopping in the middle of a document is weird. When genghis does this, do you see anything in your Apache logs?

**Comment by aboosoyeed** [comment] 2012-11-27 01:19
Apparantly yes
/usr/sbin/apache2: symbol lookup error: /usr/lib/php5/20090626/mongo.so: undefined symbol: _mongo_say

**Comment by bobthecow** [comment] 2012-11-27 01:26
Oh, heh. That's not an error I can work around :)

Try upgrading your PECL driver?

**Comment by aboosoyeed** [comment] 2012-11-27 01:55
yeah so i realised . this bug crept up towards 1.2.5v of the driver. ill
upgrade and hopefully see it vanished

**Comment by bobthecow** [comment] 2012-11-29 02:53
Since this looks like a driver issue, I'm going to close it. Feel free to reopen if you think I can do anything further on this end.

**Comment by jshueh** [comment] 2013-03-29 16:11
Sorry to bring this post back from the dead but I'm seeing the same issue.
We have a very large collection (about 200GB in size with 30 million objects).  When we try to view the last page we get the following error.  "cursor timed out (timeout: 30000, time left: 0:0, status: 0)".  The pages towards the front work ok, say page 1, even page 1000 loads.  But when we try to load the last page in the 600,000's we get a timeout.

We have tried increasing the time out via php-fpm with no success.  Is there somewhere in the Genghis code that we can increase the time out?

We are running mongo 2.4.1, with 1.3.4 php-mongo driver and Genghis 2.3.0 (php version w/ nginx)

**Comment by bobthecow** [comment] 2013-03-29 18:45
Thanks for letting me know. I'm looking into what the issue might be.

**Comment by bobthecow** [comment] 2013-03-29 18:55
Your timeout could be happening any number of places. As a stopgap, you can try changing the connect timeout by specifying it in your server connection DSN:

```
localhost:1234/?connectTimeoutMS=30000
```

... the default timeout is 1000ms, so bumping that up might help you.

From your description, though, it sounds like either a socket timeout or a server timeout, not a connect timeout, so I don't know how much that'll help you.

**Comment by jmikola** [comment] 2013-03-29 19:02
If pagination is using the cursor `limit()` and `skip()` methods, you're going to have to walk the index (assuming there is one) to get to the last page of results. For a very large collection, that process could exceed the cursor timeout, which is most certainly client-side (the server will keep cursors around for at least 15 minutes IIRC).

One alternative would be to use range queries for pagination, to pick up from the `_id` of the last document you saw. This works fine for ObjectIDs, but if you're sorting by natural order, you may be out of luck.

**Comment by bobthecow** [comment] 2013-03-29 20:27
@jshueh I just committed an option to override the default socket timeout with a server DSN option as well. Install `genghis.php` from the development branch, and add your server like this:

```
servername:1234/?socketTimeoutMS=30000
```

I'm still looking for better options, but that should at least let you work around the issue for now.

**Comment by jshueh** [comment] 2013-03-29 20:58
Thanks for the quick response!  I tired what you suggested but get the following error when trying to add the server

"PHP Strict error: Only variables should be passed by reference"

**Comment by bobthecow** [comment] 2013-03-29 21:33
Whoops. That's what I get for trying to fix things too fast. Try again with the latest :)

**Comment by jshueh** [comment] 2013-03-29 22:02
It appears to have worked, I tried a setting of 60000

When browsing to
page 1000 it took about 20 seconds to load
page 2000 it took about 35 seconds to load
page 3000 it took about 52 seconds to load
page 4000 I get "Unknown error" after 60 seconds

**Comment by bobthecow** [comment] 2013-03-30 04:46
Okay. The problem is most likely what @jmikola said, then. But even in the worst case, page 4000 is only 100k documents. You should be able to walk the index much faster than that.

Is this a search result, or just the default listing? Are you using ObjectIds or something else for your document `_id`?

**Comment by bobthecow** [comment] 2013-04-17 16:46
Closing this in favor of #104

**Closed as completed by bobthecow** 2013-04-17 16:46 UTC
Labels: bug
