### ISSUE TITLE
Unable to modify/delete documents when _id is not an ObjectId

### ISSUE THREAD

**Issue by ghost** [bobthecow/genghis#126] opened 2013-07-26 17:43 UTC
I use documented keyed used ints and genghis is unable to operate correctly in that situation.

**Comment by bobthecow** [comment] 2013-07-26 18:12
It works for me :)

Can you give me more information? Which Genghis version and backend are you running? What OS, OS version, Mongo version, Mongo driver version, etc?

**Comment by ghost** [comment] 2013-07-26 18:16
Mac OS X 10.8.4
Mongo 2.4.5

I'm updating genghisapp now, so I no longer have the old version number. Sorry about that.

**Comment by ghost** [comment] 2013-07-26 18:21
I have this document:
{
    _id: 0,
    shard: 0,
    schemaVersion: 0
}

Collection index is:
[
  {
    "v": 1,
    "key": {
      "_id": 1
    },
    "ns": "dbname.users",
    "name": "_id_"
  }
]

Modifying produces the following error in the latest genghisapp 2.3.6:
Document '~MA==' not found in 'users'

**Comment by bobthecow** [comment] 2013-07-29 00:44
I am unable to reproduce this. Can you give me more information?

Are you using the Ruby or PHP backend? What Ruby or PHP version are you using? How are you running Genghis? (behind Apache, nginx, standalone, etc).

**Comment by ghost** [comment] 2013-07-29 03:13
Ruby backend, installed via gem.
Running via "genghisapp" in the terminal

**Comment by bobthecow** [comment] 2013-07-29 03:32
What Ruby version are you running? Is it the system installed Ruby, or something like RVM or rbenv?

**Comment by ghost** [comment] 2013-07-29 03:35
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
rubygems 2.0.5

**Comment by bobthecow** [comment] 2013-07-29 04:02
That helps. Something's probably not right in Ruby 1.8.x. I was trying in 1.9.x and 2.0. I'll take a look.

**Comment by bobthecow** [comment] 2013-07-29 07:10
This should be fixed in the `hotfix/2.3.7` branch. Do you mind checking it out?

**Comment by ghost** [comment] 2013-07-29 20:29
Verified the fix in hotfix/2.3.7. Thanks

**Comment by bobthecow** [comment] 2013-07-29 20:31
Great. I'll get that released!

**Comment by ghost** [comment] 2013-07-29 20:36
Feel free to close the issue

**Closed as completed** 2013-07-29 20:39 UTC

**Comment by bobthecow** [comment] 2013-07-29 20:42
And it's released. Thanks again for the bug report.
