### ISSUE TITLE
Allow to sort

### ISSUE THREAD

**Issue by chris-zen** [bobthecow/genghis#120] opened 2013-07-03 16:36 UTC
It would be nice to be able to sort by keys. When the search box is expanded it could include a sort box where a list of keys to sort could be specified. And as a plus also a skip and limit boxes.

**Comment by bobthecow** [comment] 2013-07-03 17:42
Yep. It's in the planned-features-in-my-head list :)

**Comment by chris-zen** [comment] 2013-07-03 17:52
Nice !

**Comment by bobthecow** [comment] 2013-07-03 18:36
In an effort to save people from themselves, I might limit it to sorting by indexed fields. Or maybe only for collections over a certain size?

**Comment by chris-zen** [comment] 2013-07-05 06:19
Hmmm, good question. I would show a dialog when the size of the collection is big and there are no indices saying something like: Hi, this could take long time, bla bla, what do you want to do? [Cancel], [Go], [Create the index], [Don't ask again for this collection]
The last option would be also a global configuration option.

**Comment by andrewryno** [comment] 2013-08-09 17:36
I'd love for it to sort by anything, really. Right now I'm trying to find abnormally large numbers in my dataset as a result of a bad calculation, and the only way to find it would be by sorting (or going through many pages to find it manually). Not a really huge collection, so speed wouldn't be much of a factor in this case.

**Comment by sergiomb2** [comment] 2013-11-06 23:59
implementation of sort is good , but I also need sort fields in a document  , if a Document have many fields 
is difficult find some if it is not ordered 
ref: http://stackoverflow.com/questions/2411087/how-can-i-browse-or-query-live-mongodb-data

**Comment by mrdziuban** [comment] 2014-01-16 16:16
Any update on this or the status of the next release? I love Genghis' UI, but wish it had sorting and projection.

**Comment by bobthecow** [comment] 2014-01-16 18:29
@mrdziuban I wish it did too. I do accept pull requests if you want to speed things along :)

**Comment by bobthecow** [comment] 2014-01-18 02:07
Closing this issue as a duplicate of #58

**Closed as completed by bobthecow** 2014-01-18 02:07 UTC
Labels: feature

**Comment by bobthecow** [comment] 2014-01-18 02:15
@andrewryno I'm sure you figured it out by now, but you could find abnormally large numbers using `{foo: {$gt: 10000}}` style queries...

**Comment by andrewryno** [comment] 2014-01-18 04:04
Well the problem is when I have numbers ranging from 0-N. I don't necessarily know how large the largest "true" value is to search for mistakes. It's just easy to spot visually when sorted. But thanks for sorting!
