### ISSUE TITLE
ISODate reset on save

### ISSUE THREAD

**Issue by slykar** [bobthecow/genghis#95] opened 2013-03-27 15:33 UTC
Hello.

Seems like there is a bug when saving a document with ISODate field.
To reproduce the problem:
1. Create the following document:

```
{
    created_at: ISODate()
}
```
1. Save: The ISODate is now correct
2. Click Edit, Save: The ISODate is now wrong `1970-01-01T01:00:00+01:00``
3. Click Edit, Save: Date is now correct

**Comment by bobthecow** [comment] 2013-03-27 16:34
I'm unable to reproduce this with the current version of Genghis, with either the PHP or Ruby backend.

What is your: OS + version, Genghis version, backend language + version, browser, and MongoDB version?

**Comment by slykar** [comment] 2013-03-27 16:39
Chrome 25 @ Win 7

Server with MongoDB 2.0.4 @ Ubuntu 12.04
PHP 5.4 Genghis Version 2.3.0

**Comment by slykar** [comment] 2013-03-27 16:41
Looks like it might be Chrome related.
Works fine with FireFox.

**Comment by bobthecow** [comment] 2013-03-27 16:47
Do you mind opening the JavaScript console and watching for errors while running through that sequence?

**Comment by slykar** [comment] 2013-03-27 16:50
I did, and there's nothing. Unfortunately it fails silently...

Also, just tested with Opera 12.11. There is an "Unknown error" on the top, and when you click "Edit" you get an empty textarea.
PS. After updating to latest version of Opera the "Unknown Error" is gone, but empty textarea on edit persists.

This should go to separate issue probably.

Looks like there are some more browser related problems.

**Comment by bobthecow** [comment] 2013-03-27 16:56
Unfortunately I'm unable to reproduce it in Chrome on my Mac. I'm spinning up a Windows 7 VM and installing Chrome to try it there :)

What happens if you refresh the page between 2 and 3? Is the date correct when it loads?

What happens if you refresh between 3 and 4? Is it correct when it loads there?

**Comment by slykar** [comment] 2013-03-27 17:02
This might work better:
http://www.screenr.com/PCv7

**Comment by bobthecow** [comment] 2013-03-27 17:11
Chrome 21 and Chrome 26 work great for me on Win 7.

I am, however, able to reproduce the Opera issue. Do you mind opening another ticket for that one?

**Comment by bobthecow** [comment] 2013-03-27 17:15
Thanks for the screenr. It _seems_ like what would happen if you saved an ISODate with a something unparseable — but not null, because null would set it to the current date.

Do you mind checking your network tab for me as well? Filter it by XHR and load the page. You should see a GET for the ObjectID. Then edit the document and save, and you'll see a PUT for the same ObjectID. Check both the payload and the response for the $value key under your `created_at` property.

**Comment by slykar** [comment] 2013-03-27 17:21
GET: `{"_id":{"$genghisType":"ObjectId","$value":"515325a06803fa430a00000d"},"created_at":{"$genghisType":"ISODate","$value":"2013-03-27T18:16:36+01:00"}}`

PUT: `{"_id":{"$genghisType":"ObjectId","$value":"515325a06803fa430a00000d"},"created_at":{"$genghisType":"ISODate","$value":"1970-01-01T01:00:00+01:00"}}`

Then again GET: `{"_id":{"$genghisType":"ObjectId","$value":"515325a06803fa430a00000d"},"created_at":{"$genghisType":"ISODate","$value":"1970-01-01T01:00:00+01:00"}}`

And PUT: `{"_id":{"$genghisType":"ObjectId","$value":"515325a06803fa430a00000d"},"created_at":{"$genghisType":"ISODate","$value":"2013-03-27T18:19:27+01:00"}}`

Edit: Just checked with Chromium on my VM Ubuntu Server. Works there.
So it's my Chrome + Win combination?

Would be great if we had input from other users on this case. If this is just me, then this could be anything.
Tried to turn off all Chrome plugins - still nothing.

**Comment by bobthecow** [comment] 2013-03-27 17:44
Just for fun, try this version: http://i.0x7f.us/genghis.php-49428.zip

**Comment by slykar** [comment] 2013-03-27 17:52
OK, I've found the problem.
I earlier renamed genghis.php to index.php for whatever stupid reason.
Using filename of genghis.php solves the issue.

Sorry for troubles. Never thought it could be it.

**Comment by bobthecow** [comment] 2013-03-27 18:06
Really? I don't even understand how that could cause this problem. I've used it as `index.php` as well...

**Comment by slykar** [comment] 2013-03-27 18:07
I also do not get it, but if I use it with filename of `index.php` it does not work : )

**Comment by bobthecow** [comment] 2013-03-27 18:12
That's really strange.

I thought it might be because I was relying on an implicit string conversion of a date, so I've fixed that in `develop` just in case :)

**Comment by bobthecow** [comment] 2013-04-17 14:35
The partial/potential fix with implicit string conversion has been released in `v2.3.1`.

I am unable to reproduce your issues with renaming the php file, so I'll close this issue for now.

**Closed as completed by bobthecow** 2013-04-17 14:35 UTC
Labels: bug
